services:
  backend:
    build: ./Server
    container_name: backend_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./Server:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: docker-mysql-main # nombre del contenedor MySQL ya existente
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: dockerpass
      DB_NAME: financedb
    networks:
      - dev-network

  frontend:
    build: ./Cliente
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./Cliente:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: pnpm dev
    depends_on:
      - backend
    networks:
      - dev-network

networks:
  dev-network:
    external: true
